//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.11 at 03:19:57 PM IST 
//

package com.idbi.cpsms.succack.bean;

import java.awt.datatransfer.Transferable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BatchDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SuccessPayment" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="C5518" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="C6061" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="C6081" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="C4038" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                             &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="PmtRoute" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="C5185" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="CPSMSBatchNo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="BankCode" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="BankName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Destination" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MessageId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PaymentProduct" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RecordsCount" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="Source" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "batchDetails" })
@XmlRootElement(name = "SuccessPayments")
public class SuccessPayments {

	@XmlElement(name = "BatchDetails", required = true)
	protected SuccessPayments.BatchDetails batchDetails;
	@XmlAttribute(name = "xmlns", required = true)
	protected String xmlns;
	@XmlAttribute(name = "BankCode", required = true)
	@XmlSchemaType(name = "unsignedShort")
	protected String bankCode;
	@XmlAttribute(name = "BankName", required = true)
	protected String bankName;
	@XmlAttribute(name = "Destination", required = true)
	protected String destination;
	@XmlAttribute(name = "MessageId", required = true)
	protected String messageId;
	@XmlAttribute(name = "PaymentProduct", required = true)
	protected String paymentProduct;
	@XmlAttribute(name = "RecordsCount", required = true)
	@XmlSchemaType(name = "unsignedByte")
	protected int recordsCount;
	@XmlAttribute(name = "Source", required = true)
	@XmlSchemaType(name = "unsignedShort")
	protected String source;

	/**
	 * Gets the value of the batchDetails property.
	 * 
	 * @return possible object is {@link SuccessPayments.BatchDetails }
	 * 
	 */
	public SuccessPayments.BatchDetails getBatchDetails() {
		return batchDetails;
	}

	/**
	 * Sets the value of the batchDetails property.
	 * 
	 * @param value allowed object is {@link SuccessPayments.BatchDetails }
	 * 
	 */
	public void setBatchDetails(SuccessPayments.BatchDetails value) {
		this.batchDetails = value;
	}

	/**
	 * Gets the value of the bankCode property.
	 * 
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * Sets the value of the bankCode property.
	 * 
	 */
	public void setBankCode(String value) {
		this.bankCode = value;
	}

	/**
	 * Gets the value of the bankName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * Sets the value of the bankName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBankName(String value) {
		this.bankName = value;
	}

	/**
	 * Gets the value of the destination property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDestination() {
		return destination;
	}

	/**
	 * Sets the value of the destination property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setDestination(String value) {
		this.destination = value;
	}

	/**
	 * Gets the value of the messageId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMessageId() {
		return messageId;
	}

	/**
	 * Sets the value of the messageId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMessageId(String value) {
		this.messageId = value;
	}

	/**
	 * Gets the value of the paymentProduct property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPaymentProduct() {
		return paymentProduct;
	}

	/**
	 * Sets the value of the paymentProduct property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPaymentProduct(String value) {
		this.paymentProduct = value;
	}

	/**
	 * Gets the value of the recordsCount property.
	 * 
	 */
	public int getRecordsCount() {
		return recordsCount;
	}

	/**
	 * Sets the value of the recordsCount property.
	 * 
	 */
	public void setRecordsCount(int value) {
		this.recordsCount = value;
	}

	/**
	 * Gets the value of the source property.
	 * 
	 */
	public String getSource() {
		return source;
	}

	/**
	 * Sets the value of the source property.
	 * 
	 */
	public void setSource(String value) {
		this.source = value;
	}
	

	public String getXmlns() {
		return xmlns;
	}

	public void setXmlns(String xmlns) {
		this.xmlns = xmlns;
	}

	@Override
	public String toString() {
		return "SuccessPayments [batchDetails=" + batchDetails + ", xmlns=" + xmlns + ", bankCode=" + bankCode
				+ ", bankName=" + bankName + ", destination=" + destination + ", messageId=" + messageId
				+ ", paymentProduct=" + paymentProduct + ", recordsCount=" + recordsCount + ", source=" + source + "]";
	}
	

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="SuccessPayment" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="C5518" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="C6061" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
	 *                   &lt;element name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                   &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                   &lt;element name="C6081" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="C4038" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
	 *                   &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
	 *                   &lt;element name="PmtRoute" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="C5185" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
	 *       &lt;attribute name="CPSMSBatchNo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "successPayment" })
	public static class BatchDetails {

		@XmlElement(name = "SuccessPayment", required = true)
		protected List<SuccessPayments.BatchDetails.SuccessPayment> successPayment;
		@XmlAttribute(name = "C5185", required = true)
		@XmlSchemaType(name = "unsignedByte")
		protected String c5185;
		@XmlAttribute(name = "CPSMSBatchNo", required = true)
		protected String cpsmsBatchNo;

		/**
		 * Gets the value of the successPayment property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the successPayment property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getSuccessPayment().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link SuccessPayments.BatchDetails.SuccessPayment }
		 * 
		 * 
		 */
		public List<SuccessPayments.BatchDetails.SuccessPayment> getSuccessPayment() {
			if (successPayment == null) {
				successPayment = new ArrayList<SuccessPayments.BatchDetails.SuccessPayment>();
			}
			return this.successPayment;
		}

		public void setSuccessPayment(List<SuccessPayments.BatchDetails.SuccessPayment> successPayment) {
			this.successPayment = successPayment;
		}

		/**
		 * Gets the value of the c5185 property.
		 * 
		 */
		public String getC5185() {
			return c5185;
		}

		/**
		 * Sets the value of the c5185 property.
		 * 
		 */
		public void setC5185(String value) {
			this.c5185 = value;
		}

		/**
		 * Gets the value of the cpsmsBatchNo property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCPSMSBatchNo() {
			return cpsmsBatchNo;
		}

		/**
		 * Sets the value of the cpsmsBatchNo property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setCPSMSBatchNo(String value) {
			this.cpsmsBatchNo = value;
		}

		@Override
		public String toString() {
			return "BatchDetails [successPayment=" + successPayment + ", c5185=" + c5185 + ", cpsmsBatchNo="
					+ cpsmsBatchNo + "]";
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="C2020" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="C2006" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="C5518" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="C6061" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
		 *         &lt;element name="BankIIN" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *         &lt;element name="C6081" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="C4038" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
		 *         &lt;element name="C6346" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="C3501" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
		 *         &lt;element name="PmtRoute" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "c2020", "c2006", "c6061", "uid","bankIIN", "c5518", "c6081", "c4038",
				"c6346", "c3501", "pmtRoute" })
		public static class SuccessPayment {

			@XmlElement(name = "C2020", required = true)
			protected String c2020;
			@XmlElement(name = "C2006", required = true)
			protected String c2006;
			@XmlElement(name = "C5518", required = true)
			protected String c5518;
			@XmlElement(name = "C6061", required = true)
			@XmlSchemaType(name = "unsignedLong")
			protected String c6061;
			@XmlElement(name = "BankIIN", required = true)
			protected String bankIIN;
			@XmlElement(name = "UID", required = true)
			protected String uid;
			@XmlElement(name = "C6081", required = true)
			protected String c6081;
			@XmlElement(name = "C4038")
			@XmlSchemaType(name = "unsignedShort")
			protected String c4038;
			@XmlElement(name = "C6346", required = true)
			protected String c6346;
			@XmlElement(name = "C3501", required = true)
			@XmlSchemaType(name = "unsignedLong")
			protected String c3501;
			@XmlElement(name = "PmtRoute", required = true)
			protected String pmtRoute;

			/**
			 * Gets the value of the c2020 property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getC2020() {
				return c2020;
			}

			/**
			 * Sets the value of the c2020 property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setC2020(String value) {
				this.c2020 = value;
			}

			/**
			 * Gets the value of the c2006 property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getC2006() {
				return c2006;
			}

			/**
			 * Sets the value of the c2006 property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setC2006(String value) {
				this.c2006 = value;
			}

			/**
			 * Gets the value of the c5518 property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getC5518() {
				return c5518;
			}

			/**
			 * Sets the value of the c5518 property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setC5518(String value) {
				this.c5518 = value;
			}

			/**
			 * Gets the value of the c6061 property.
			 * 
			 * @return possible object is {@link BigInteger }
			 * 
			 */
			public String getC6061() {
				return c6061;
			}

			/**
			 * Sets the value of the c6061 property.
			 * 
			 * @param value allowed object is {@link BigInteger }
			 * 
			 */
			public void setC6061(String value) {
				this.c6061 = value;
			}

			/**
			 * Gets the value of the bankIIN property.
			 * 
			 * @return possible object is {@link Object }
			 * 
			 */
			public String getBankIIN() {
				return bankIIN;
			}

			/**
			 * Sets the value of the bankIIN property.
			 * 
			 * @param value allowed object is {@link Object }
			 * 
			 */
			public void setBankIIN(String value) {
				this.bankIIN = value;
			}

			/**
			 * Gets the value of the uid property.
			 * 
			 * @return possible object is {@link Object }
			 * 
			 */
			public String getUID() {
				return uid;
			}

			/**
			 * Sets the value of the uid property.
			 * 
			 * @param value allowed object is {@link Object }
			 * 
			 */
			public void setUID(String value) {
				this.uid = value;
			}

			/**
			 * Gets the value of the c6081 property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getC6081() {
				return c6081;
			}

			/**
			 * Sets the value of the c6081 property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setC6081(String value) {
				this.c6081 = value;
			}

			/**
			 * Gets the value of the c4038 property.
			 * 
			 */
			public String getC4038() {
				return c4038;
			}

			/**
			 * Sets the value of the c4038 property.
			 * 
			 */
			public void setC4038(String value) {
				this.c4038 = value;
			}

			/**
			 * Gets the value of the c6346 property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getC6346() {
				return c6346;
			}

			/**
			 * Sets the value of the c6346 property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setC6346(String value) {
				this.c6346 = value;
			}

			/**
			 * Gets the value of the c3501 property.
			 * 
			 * @return possible object is {@link BigInteger }
			 * 
			 */
			public String getC3501() {
				return c3501;
			}

			/**
			 * Sets the value of the c3501 property.
			 * 
			 * @param value allowed object is {@link BigInteger }
			 * 
			 */
			public void setC3501(String value) {
				this.c3501 = value;
			}

			/**
			 * Gets the value of the pmtRoute property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPmtRoute() {
				return pmtRoute;
			}

			/**
			 * Sets the value of the pmtRoute property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setPmtRoute(String value) {
				this.pmtRoute = value;
			}

			@Override
			public String toString() {
				return "SuccessPayment [c2020=" + c2020 + ", c2006=" + c2006 + ", c5518=" + c5518 + ", c6061=" + c6061
						+ ", bankIIN=" + bankIIN + ", uid=" + uid + ", c6081=" + c6081 + ", c4038=" + c4038 + ", c6346="
						+ c6346 + ", c3501=" + c3501 + ", pmtRoute=" + pmtRoute + "]";
			}

		}

	}

}
